language: rust
rust:
  - beta
  - nightly
script:
  - make all
  - make travistest

env:
  matrix:
    -
    - RELEASE=true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ec2440f26c71d930f26c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
