[package]
name = "mioco"
version = "0.0.4"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Coroutine-based AIO handling for Rust"
keywords = ["mio", "aio", "io", "coroutine"]
license = "MPL-2.0"
documentation = "https://dpc.github.io/mioco/"
homepage = "https://github.com/dpc/mioco"
repository = "https://github.com/dpc/mioco"
readme = "README.md"


[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[lib]
name = "mioco"
path = "src/lib.rs"

[dependencies]
nix = "*"
coroutine = "*"
log = "*"
env_logger = "*"

[dependencies.mio]
git = "https://github.com/carllerche/mio"
