[package]
name = "mioco"
version = "0.1.0-rc1pre"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Scalable, asynchronous IO coroutine-based handling (aka MIO COroutines)."
keywords = ["mio", "aio", "io", "coroutine"]
license = "MPL-2.0"
documentation = "https://dpc.github.io/mioco/"
homepage = "https://github.com/dpc/mioco"
repository = "https://github.com/dpc/mioco"
readme = "README.md"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[lib]
name = "mioco"
path = "src/lib.rs"

[dependencies]
nix = "*"
log = "*"
env_logger = "*"
spin = "*"
mio = "0.4.*"
time = "*"

#bit-vec = "*"
[dependencies.bit-vec]
git = "https://github.com/dpc/bit-vec"

#coroutine = "*"
[dependencies.coroutine]
git = "https://github.com/rustcc/coroutine-rs.git"
