[package]
name = "mioco"
version = "0.2.0-pre1"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Scalable, asynchronous IO coroutine-based handling (aka MIO COroutines)."
keywords = ["mio", "aio", "io", "coroutine", "async"]
license = "MPL-2.0"
documentation = "https://dpc.github.io/mioco/"
homepage = "https://github.com/dpc/mioco"
repository = "https://github.com/dpc/mioco"
readme = "README.md"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[lib]
name = "mioco"
path = "src/lib.rs"

[dependencies]
nix = "*"
log = "*"
spin = "*"
time = "*"
mio = "*"
num_cpus = "*"
libc = "^0.1.10"
thread-scoped = "*"
context = "*"
slab = "*"

[dev-dependencies]
env_logger = "*"
httparse = "*"
